version: "3.8"

name: elastic

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms${ELASTIC_HEAP} -Xmx${ELASTIC_HEAP}
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports:
      - "${ELASTIC_HTTP}:9200"
    volumes:
      - ${ELASTIC_DATA}:/usr/share/elasticsearch/data
      - ${ELASTIC_CERTS}:/usr/share/elasticsearch/config/certs:ro
    networks:
      - ${SIEM_NET}

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    depends_on: [elasticsearch]
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=["https://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - SERVER_PUBLICBASEURL=https://kibana.local:${KIBANA_PORT}
      - SERVER_SSL_ENABLED=false
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - ${SIEM_NET}

networks:
  ${SIEM_NET}:
    external: true
